### ISSUE TITLE
I can not recognise which chromsome is which.

### ISSUE THREAD

**Issue by bioinformaticspcj** [jianlin-cheng/GenomeFlow#1]
Dear author:

Thanks for the useful program. Now I meet a problem that I reconstructed the 3D struction of the 13 chromsome, but I can not distinguish which chromsome is chromsome. In addition, I want to lable the genes in chromsomes out, what should I do?

Thanks again.
Looking forward to your valuable reply.
best wishes

**Comment by tuantrieu** [comment]
You can open the console ( File > Console) and click on any point to see chromosome and location of the point displayed in the console (e.g. <Chr(21), Loc(42000000-42500000))

Chromosomes are labeled in alphabet (chr.1 as A, chr.2 as B, etc.). In the console, you can select chromosome 1 by: select chain=A, then label it by: label A. These functions are inherited from Jmol, you can check out Jmol's documentation.

**Comment by tuantrieu** [comment]
Hover mouse over the point also shows coordinate

**Comment by tuantrieu** [comment]
You can open the console ( File > Console) and click on any point to see chromosome and location of the point displayed in the console (e.g. <Chr(21), Loc(42000000-42500000)). Hover mouse over the point also shows coordinate

Chromosomes are labeled in alphabet (chr.1 as A, chr.2 as B, etc.). In the console, you can select chromosome 1 by: select chain=A, then label it by: label A. These functions are inherited from Jmol, you can check out Jmol's documentation.

To annotate genes, please look at 3D-Functions > Model Annotation (https://github.com/jianlin-cheng/GenomeFlow/wiki/3D-Functions)

**Comment by bioinformaticspcj** [comment]
Hi,
Thanks for your valuable advice.
I used the command "select chain=A label Chr1" to label the chromsom, but I found that the density of the labels was very high(see the attached picture). It is not clear because there are so many "Chr1s" emerging through the chromsome. I do not know how to make it clear to label one chromsome with only one unique label other than label one chromsome with many repeated lables.&nbsp;


Thanks again.


Looking for your timely reply.


Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tuantrieu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月13日(星期天) 中午12:05
收件人:&nbsp;"jianlin-cheng/GenomeFlow"<GenomeFlow@noreply.github.com&gt;;
抄送:&nbsp;"Monkeyjun"<2532090267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jianlin-cheng/GenomeFlow] I can not recognise which chromsome is which. (#1)




You can open the console ( File &gt; Console) and click on any point to see chromosome and location of the point displayed in the console (e.g. <Chr(21), Loc(42000000-42500000)). Hover mouse over the point also shows coordinate
 
Chromosomes are labeled in alphabet (chr.1 as A, chr.2 as B, etc.). In the console, you can select chromosome 1 by: select chain=A, then label it by: label A. These functions are inherited from Jmol, you can check out Jmol's documentation.
 
To annotate genes, please look at 3D-Functions &gt; Model Annotation (https://github.com/jianlin-cheng/GenomeFlow/wiki/3D-Functions)

**Comment by tuantrieu** [comment]
You can select one atom of each chromosome (just click on an atom) and label it. These features are inherited from Jmol (https://chemapps.stolaf.edu/jmol/docs/), you can refer to Jmol's document for more detail.

**Comment by bioinformaticspcj** [comment]
Got it. Thanks a lot.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tuantrieu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 凌晨3:25
收件人:&nbsp;"jianlin-cheng/GenomeFlow"<GenomeFlow@noreply.github.com&gt;;
抄送:&nbsp;"Monkeyjun"<2532090267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jianlin-cheng/GenomeFlow] I can not recognise which chromsome is which. (#1)




You can select one atom of each chromosome (just click on an atom) and label it. These features are inherited from Jmol (https://chemapps.stolaf.edu/jmol/docs/), you can refer to Jmol's document for more detail.
